version: "3.8"

services:
  go:
    container_name: leboncoin_go_server
    image: edjubert/leboncoin
    networks:
      fizzbuzz:
    ports:
      - "8080:8000"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

  redis:
    container_name: leboncoin_redis_server
    image: redis
    ports:
      - "6379:6379"
    networks:
      fizzbuzz:
    volumes:
      - data:/data

networks:
  fizzbuzz:

volumes:
  data:
