version: "3.8"

services:
  go:
    container_name: fizzbuzz_go_server
    image: edjubert/fizzbuzz
    networks:
      fizzbuzz:
    ports:
      - "8080:8000"
      - "8081:8001"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

  redis:
    container_name: fizzbuzz_redis_server
    image: redis
    ports:
      - "6381:6379"
    networks:
      fizzbuzz:
    volumes:
      - data:/data

networks:
  fizzbuzz:

volumes:
  data:
